branches:
  - name: main

plugins:
  - '@semantic-release/commit-analyzer'
  - - '@semantic-release/npm'
    - pkgRoot: './package'
  - '@semantic-release/git'
  - - '@semantic-release/github'
    - assets:
        - 'package/**'
