branches:
  - name: main

plugins:
  - '@semantic-release/commit-analyzer'
  - "@semantic-release/release-notes-generator"
  - - '@semantic-release/changelog'
    - changelogFile: 'CHANGELOG.md'
  - - '@semantic-release/npm'
    - pkgRoot: './package'
  - - '@semantic-release/git'
    - assets: ['CHANGELOG.md']
  - - '@semantic-release/github'
    - assets:
        - 'package/**'
